FROM base-image:latest
LABEL maintainer="The Palace Project <info@thepalaceproject.org>"

ENV SIMPLIFIED_DB_TASK "ignore"
ENV LANG=C.UTF-8

RUN /bin/bash -c "/ls_build/nginx.sh \
      && /ls_build/uwsgi.sh \
      && rm -rf /ls_build && /bd_build/cleanup.sh"

VOLUME /var/log
WORKDIR /home/simplified/circulation
EXPOSE 80

CMD ["/sbin/my_init"]

# # If you launch the container interactively with `docker run -it`,
# # this is where you'll end up:
# ENTRYPOINT ["/bin/bash"]
